### ISSUE TITLE
another nitpick in README

### ISSUE THREAD

**Issue by sydb** [schxslt/schxslt-ant#10]
The JAR file listed in the README is “ant-schxsl-1.3.jar”. The JAR file available for download from the “releases” section is “ant-schxsl**t**-1.3.jar”. That missing ‘t’ can be a health hazard. (And personally, I prefer it with the ‘t’, but matching is more important than my preference.)

It would also be nice if the README told the reader explicitly from where to download the JAR file; and gave  the reader either instructions on how to create (“compile” to) a JAR file, or a pointer to such instructions. (I realize it is not your job to teach java to those of us who are java-impaired, but a little advice could go a long way … :-)

**Comment by dmj** [comment]
Thanks for reporting! I did update the README with a section on installing and compiling the task.

**Comment by sydb** [comment]
Excellent, thank you.

I still can't run it from Ant, but will try building and using 1.4 and see if that works. (Oooh! Just noticed 1.4 is now released. Will try that …)
