### ISSUE TITLE
Ant task on Maven Central

### ISSUE THREAD

**Issue by nkutsche** [schxslt/schxslt-ant#4]
Hi,

we evaluate different Schematron AntTask implementations to use them in our projects. One requirement would be that they are available on a public Maven repository (e.g. Maven Central). I noticed that the main artifacts of schXslt are on Maven Central but this not. 
Is there a reason for? Or did I missed something?

Thanks!
Nico

**Comment by dmj** [comment]
No, there is no reason for it. Will be done soon.

**Comment by dmj** [comment]
Done: https://search.maven.org/artifact/name.dmaus.schxslt/ant Please let me know if you discover any bugs or glitches.

**Comment by nkutsche** [comment]
Great thanks! We will definitly try it.
